### ISSUE TITLE
support swift 2.0

### ISSUE THREAD

**Issue by REZ1DENT3** [ykyouhei/KYDrawerController#10]
Hello. 
He started to develop the application. Really liked the implementation of DrawerController. When will support Swift 2.0?

**Comment by ykyouhei** [comment]
@REZ1DENT3 
Hi,
Thunk you!
It is scheduled to be implemented at the end of this week. 
Please wait a moment.

**Comment by ykyouhei** [comment]
@REZ1DENT3 
Hello.
supported swift2.0. Please try! :+1: 
https://github.com/ykyouhei/KYDrawerController/releases/tag/1.1.0-bata.3

**Comment by REZ1DENT3** [comment]
Hello. Thank you very much!
