### ISSUE TITLE
Unable to compile in Swift4 and XCode 9.0 (9A1004)

### ISSUE THREAD

**Issue by maxivu** [ykyouhei/KYDrawerController#107]
Getting following error after POD install and clean build

<project root>/Pods/KYDrawerController/KYDrawerController/Classes/KYDrawerController.swift:106:21: Argument of '#selector' refers to instance method 'didtapContainerView' that is not exposed to Objective-C

<project root>/Pods/KYDrawerController/KYDrawerController/Classes/KYDrawerController.swift:84:21: Argument of '#selector' refers to instance method 'handlePanGesture' that is not exposed to Objective-C

<project root>/Pods/KYDrawerController/KYDrawerController/Classes/KYDrawerController.swift:97:21: Argument of '#selector' refers to instance method 'handlePanGesture' that is not exposed to Objective-C

**Comment by burkaslarry** [comment]
add   @objc func before 'handlePanGesture' or rewrite the selector . It is the stack-overflow type question

**Comment by burkaslarry** [comment]
Yet creating your own slider view is easy . I create one view controller with storyboard  as slider menu and one more custom delegate. I doubt why such GitHub module requires much more settings and complexity

**Comment by timusus** [comment]
@ykyouhei looks like this issue has bee resolved in #104
