### ISSUE TITLE
On item select to leave the drawer open

### ISSUE THREAD

**Issue by snc001** [ykyouhei/KYDrawerController#114]
Hi guys,

I was wondering if there was a way to change or update the view dynamically depending on what has been selected?

![modify this](https://user-images.githubusercontent.com/12015902/38942163-3d342154-4382-11e8-8902-2206d7143347.png)

Eg. First row of the side draw is selected and the view below the profile area fully changes

**Comment by timusus** [comment]
This looks to me like a question about iOS development / layouts in general, and not specific to this library.

@ykyouhei recommend closing this issue.
