### ISSUE TITLE
initiate drawer to a different view

### ISSUE THREAD

**Issue by snc001** [ykyouhei/KYDrawerController#117]
Is there a way to initiate the draw to a different view?

Example
- you have a login view and a main view plus a drawer view

- initiate drawer after the login view is passed to the main view

Currently you have to initiate the drawer from AppDelegate which has to set drawer controller as rootview.

Though this only takes 2 controllers - whatever view you want the drawer on and the drawer controller.

So is there a way to make it so that the drawer can be initiated else where?

**Comment by timusus** [comment]
You don't _have_ to instantiate the `KYDrawerController` in `AppDelegate`, that is just an example of how this controller can be used. You can place the `KYDrawerController` anywhere you like, you just have to pass it a reference to whatever controller you want to use as the `MainController` and `DrawerViewController`.

@ykyouhei recommend closing this issue.
