### ISSUE TITLE
How to open drawer on button click 

### ISSUE THREAD

**Issue by pawarn** [ykyouhei/KYDrawerController#118]
I am new to IOS App development.  I used this library in my project and setup from the storyboard.

Now I added on hamburger icon on the navigation bar and on click on Hamburger icon I want to open drawer just like an android.

How can I achieve this?

Thanks for the help in advanced.

**Comment by timusus** [comment]
From the readme:

Open/close drawer:
`func setDrawerState(state: DrawerState, animated: Bool)`

You'll need to call that function when your hamburger icon is clicked. This is _probably_ demonstrated in the example.

**Comment by pawarn** [comment]
Thanks,

I achieve this using following code.

if let drawerController = navigationController?.parent as? KYDrawerController {
            drawerController.setDrawerState(.opened, animated: true)
        }
