### ISSUE TITLE
Getting black screen of main controller

### ISSUE THREAD

**Issue by bhavuk-webkul** [ykyouhei/KYDrawerController#131]
Getting black screen of main controller 
http://prntscr.com/lnwph5

**Comment by snc001** [comment]
Is it because your drawer background is black and is taking all the screen real estate?

meaning if your drawer width that you're using is say... 300/414 but you've made your side drawer view on the storyboard to be 414 and the background is black then thats what it'll be.

**Comment by bhavuk-webkul** [comment]
any update

**Comment by snc001** [comment]
limit 260 for your drawer and make the mainview normal size.
Else it won't know how to populate

**Comment by anonym24** [comment]
In my case I can't even open drawer and everything from ui view controller is gone (no items on toolbar, uiviewcontroller is black)

It just makes my content black and top bar gray

**Comment by anonym24** [comment]
it seems that we have to set initial VC as `KYDrawerController` and not `UIViewController`

**Comment by anonym24** [comment]
@snc001 what do you mean? 

I have used a default value 200 and what I get is https://github.com/ykyouhei/KYDrawerController/issues/139

@bhavuk-webkul did you solve this issue?

**Comment by bhavuk-webkul** [comment]
yes i have solved this issue
