### ISSUE TITLE
Update to swift 2?

### ISSUE THREAD

**Issue by plummer** [ykyouhei/KYDrawerController#14]
Happy to do a PR to update this to swift 2

**Comment by ykyouhei** [comment]
@plummer Hi!
After the official version xcode7 has been released , it plans to merge to master.
https://github.com/ykyouhei/KYDrawerController/tree/feature-swift2.0
https://github.com/ykyouhei/KYDrawerController/releases/tag/1.1.0-beta5

**Comment by seapy** [comment]
@ykyouhei official version xcode7 released ~

**Comment by ykyouhei** [comment]
@plummer @seapy 
Hi, Thank you!swift2 it was supported!
https://github.com/ykyouhei/KYDrawerController/releases/tag/1.1.0
