### ISSUE TITLE
support for iOS 7?

### ISSUE THREAD

**Issue by kohdesmond** [ykyouhei/KYDrawerController#15]
Hi @ykyouhei,

thanks for the awesome library, jus wondering if you are supporting iOS7?

**Comment by ykyouhei** [comment]
Hi. @kohdesmond 
If libraries that are implemented in the swift, the installation of at cocoapods does not support ios7.
http://stackoverflow.com/questions/29943911/include-pods-from-swift-sources-in-ios7-swift-project

If you want to support ios7 , please add the source code directly to the project .
https://github.com/ykyouhei/KYDrawerController#manually
