### ISSUE TITLE
Prevent menu from opening

### ISSUE THREAD

**Issue by sadanro100** [ykyouhei/KYDrawerController#17]
In order to prevent the menu from opening in specific ViewControllers I had to set the menu width to 0 and set it to .Closed when the delegate tells me it's been opened.

Besides not being elegant, the dark overlay appears for a slight moment.

Any other way around it?

Thanks.

**Comment by sadanro100** [comment]
Tried to prevent it in handlePanGesture of KYDrawerControllerDelegate but I am unable to determine which viewController is being displayed. That's actually something I am going to be needing quite a lot.

UIApplication.sharedApplication().keyWindow?.rootViewController always gives me KYDrawerController
UIApplication.sharedApplication().keyWindow?.rootViewController?.presentedViewController is always nil

Any thoughts? Thanks a lot.

**Comment by sadanro100** [comment]
Ok, this is how I solved it. Added this as first thing in handlePanGesture. Let me know if there's another option please...

let drawerVC = UIApplication.sharedApplication().keyWindow?.rootViewController as! KYDrawerController
        let mainVC = drawerVC.mainViewController
        if (mainVC.isKindOfClass(UINavigationController)) {
            let rootVC = (mainVC as! UINavigationController).viewControllers[0]
            let visibleVC = (mainVC as! UINavigationController).visibleViewController
            if (visibleVC != rootVC) { return }
        }

**Comment by ykyouhei** [comment]
@sadanro100 Hi!
I wanted to try to add a flag to disable the gesture .

```Swift
public class KYDrawerController: UIViewController, UIGestureRecognizerDelegate {
    :
    var screenEdgePanGestureEnabled: Bool
    :
}
````

Please wait a while.

**Comment by ykyouhei** [comment]
@sadanro100 Hi.
I've solved the problem . Please check :+1: 
https://github.com/ykyouhei/KYDrawerController/releases/tag/1.1.1

**Comment by sadanro100** [comment]
Thank you very much for you attention and help.

:)

**Comment by zishanj** [comment]
sample code on [#123](https://github.com/ykyouhei/KYDrawerController/issues/123#issuecomment-524535700)
