### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by hardikdevios** [ykyouhei/KYDrawerController#19]
One request for this great lib that is it possible to display drawer below Navigation bar ? so that it becomes side menu under Navigation bar.

For Eg
http://i.stack.imgur.com/Zz5EX.png

**Comment by ykyouhei** [comment]
sorry , in the current View hierarchy , it seems hard to achieve it...

**Comment by hardikdevios** [comment]
@ykyouhei  i Already managed to do that bro :+1:
