### ISSUE TITLE
Does KYDrawerController support State preservation/restoration?

### ISSUE THREAD

**Issue by haducloc** [ykyouhei/KYDrawerController#20]
Thank you for very awesome drawer. I have a question. Does KYDrawerController support State preservation/restoration?

**Comment by hardikdevios** [comment]
Nope its not supported currently you have to managed it manually

**Comment by ykyouhei** [comment]
You can be disabled for the gesture to open the drawer.
https://github.com/ykyouhei/KYDrawerController/issues/17

Because I English is not good , it may not be the answer you are expecting

**Comment by harshitgupta** [comment]
hey @hardikdevios,

I tried to do it manually for couldn't get it working.

Can you please post some helping code?
