### ISSUE TITLE
Will the KYDrawerCotroller work with a tabbed bar application ?

### ISSUE THREAD

**Issue by aziz-boudi4** [ykyouhei/KYDrawerController#21]
Hi, I have a tabbed bar application with 5 tabs.

Each view controller is embedded in a navigation controller.

Will the KYDrawerController be compatible with this kind of configuration?  

So basically I would like to have it in each view controller.

![screen shot 2015-10-24 at 11 10 55 pm](https://cloud.githubusercontent.com/assets/7435015/10714272/3db77b20-7aa4-11e5-927b-ba0f6abb305b.png)

**Comment by hardikdevios** [comment]
@aziz-boudi4 probably yes you just give your main segue to the tabbarController but still we need to confirm with main Author Also one question from my side basically why you want to use KYDrawer if your purpose being solved with tabbar options

**Comment by ykyouhei** [comment]
@aziz-boudi4 
It can be achieved by setting the tabbarController to KYDrawerController.mainViewController.

@hardikdevios Thanks :+1:

**Comment by htarwara6245** [comment]
Can you provide example like the above image in swift?Also,how to disable Drawer Gesture on some view?

**Comment by shahidmohd31** [comment]
@htarwara6245  how are you?
hope you have implemented the desired thing,am to stuck here,could you plz help?
