### ISSUE TITLE
Setup drawer right side does not work

### ISSUE THREAD

**Issue by haducloc** [ykyouhei/KYDrawerController#22]
Hi. Thank you again for the awesome drawer.

I have a question. I want to setup drawer on right side. I am using your code example but it does not work ( when I clicked on Open button, No drawer displayed from right side)

    drawerController.drawerDirection = .Right
    drawerController.drawerWidth     = 200

Do I have do anything in order to make Right-Drawer work?

Thanks!

**Comment by hardikdevios** [comment]
@haducloc  can you tell us bit more , are you setting using the code or with storyboard?

**Comment by haducloc** [comment]
I am not using Storyboard. What I did setup as below:

func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        // Override point for customization after application launch.

        let mainViewController   = MainViewController()
        let drawerViewController = DrawerViewController()
        let drawerController     = KYDrawerController()
        drawerController.mainViewController = UINavigationController(
            rootViewController: mainViewController
        )
        drawerController.drawerViewController = drawerViewController

        // To make Right Drawer
        drawerController.drawerDirection = .Right
        drawerController.drawerWidth     = 200

        window = UIWindow(frame: UIScreen.mainScreen().bounds)
        window?.rootViewController = drawerController
        window?.makeKeyAndVisible()

        return true
    }

**Comment by ykyouhei** [comment]
@haducloc Hi!
As shown below , please try to change the order in which to set the drawerDirection.

```Swift
let drawerController     = KYDrawerController()

// To make Right Drawer
drawerController.drawerDirection = .Right
drawerController.drawerWidth     = 200

drawerController.mainViewController = UINavigationController(
    rootViewController: mainViewController
)
drawerController.drawerViewController = drawerViewController
```

I'm sorry, but for this bug will at a later date will correspond

@hardikdevios Thanks! :+1:

**Comment by haducloc** [comment]
Thank you ykyouhei. I will test it

**Comment by shaniceweiwei** [comment]
how can i set it to the right side with Storyboard? @haducloc
