### ISSUE TITLE
Changing the frame Y

### ISSUE THREAD

**Issue by Ritooon** [ykyouhei/KYDrawerController#23]
Hi ! 
First, it's a really nice project :) 

Secondly, is it possible to easily change the position of the view ? I mean, the y origin. 

Regards !

**Comment by Ritooon** [comment]
Oh, I found how to manage ... :) 

In fact if you know the position of you're navigation bar, you can easily manage it by modifying the KYDrawerController class doing this (65 is the position + the height of my nav bar) : 

`view.addConstraints(
            NSLayoutConstraint.constraintsWithVisualFormat(
                "V:|-(<=65)-[_containerView]-0-|",
                options: [],
                metrics: nil,
                views: viewDictionary
            )
        )`

**Comment by hardikdevios** [comment]
@Ritooon Great buddy i know what you are trying to achieve see my question #19 , i have done exactly the same in order to display the Drawer Below Navigation bar :+1:  cheers buddy its a great Lib very smooth and easily customizable

**Comment by Ritooon** [comment]
@hardikdevios Yes, it's great library ! The best I have found until now ;)
