### ISSUE TITLE
Animation issue - Changing drawerViewController and direction respectively.

### ISSUE THREAD

**Issue by harshitgupta** [ykyouhei/KYDrawerController#24]
Hi, 

Thanks for the awesome project. Even more for sharing it with the community.

My scenario:
1. One Naviagtion controller in center as mainViewController.
2. Two side bar menu controller, i.e. left and right.
3. In Navigation bar, I have two bar button items on each side. One(on the left) to reveal 'main' menu from left and the other(on the right) to reveal 'sub' menu from right.

Since the orignal 'KYdrawerController' project only supports one side for the moment, so I am using a workaround for now.

I keep both side view controllers ready. Whenever user presses either of the button in navigation bar. I change the drawerViewController and drawerDirection properties with respective viewcontroller and direction.

It is working fine. The issue is when user presses the right menu button for the first time, it seems the viewcontroller takes a flight from far left side to the far right side first, then reveals itself from there.

Code for setting leftsidebar

![screen shot 2015-10-28 at 3 58 57 pm](https://cloud.githubusercontent.com/assets/1644577/10802822/e3b406de-7d8c-11e5-9bf3-21fcdbe1d1ed.png)

Code for setting rightsidebar

![screen shot 2015-10-28 at 3 58 47 pm](https://cloud.githubusercontent.com/assets/1644577/10802840/fa1dbb54-7d8c-11e5-9105-059a4c6b9055.png)

Note: 1.  It only happens for the first time. After that it runs fine.
          2. I am using swift files in objective C project. (Dont think it matters though.)

Please suggest something.

Thanks.

**Comment by hardikdevios** [comment]
@harshitgupta could you please share a Demo project or any Gif animation ?

**Comment by ykyouhei** [comment]
@harshitgupta Hi!
I was able to reproduce the problem .
I think due to the fact that animation has been started before the constraints of view is updated..
Sorry..It is difficult to be solved soon.

@hardikdevios Thank you always :smile:

**Comment by ykyouhei** [comment]
@harshitgupta 
This is the first aid , but it is likely to be avoided in the code shown below.
```ObjC
:
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, 0.01f * NSEC_PER_SEC),dispatch_get_main_queue(), ^{
    [self.ky_drawerController setDrawerState: DrawerStateOpened animated: YES];
});
```

**Comment by harshitgupta** [comment]
thanks a lot @ykyouhei and @hardikdevios 

The code worked.

I was able to avoid the issue when the main viewcontroller was a part of UINavigationController hierarchy, by setting up drawerViewController property a bit earlier rather than just before opening it. Like in viewDidLoad or something. It worked perfectly fine there. But the same won't work in case of TabBarController. 

Thanks again. 

A lilte feedback, I believe blocks would be better than delegates.

**Comment by hardikdevios** [comment]
:+1:  Big cheers to Author @ykyouhei
