### ISSUE TITLE
Strange behavior 

### ISSUE THREAD

**Issue by chlebta** [ykyouhei/KYDrawerController#26]
Her's how I've implemented the library : 
```
        let drawerController     = KYDrawerController()
        
        drawerController.mainViewController = UINavigationController(
            rootViewController: tabBarController
        )
        drawerController.drawerViewController = menuController
        drawerController.drawerDirection = .Right

        /* Customize
        drawerController.drawerDirection = .Right
        drawerController.drawerWidth     = 200
        */
        
        window = UIWindow(frame: UIScreen.mainScreen().bounds)
        window?.rootViewController = drawerController
        window?.makeKeyAndVisible()
        
```
![strange](https://cloud.githubusercontent.com/assets/1204608/10963954/400c4f6e-83a4-11e5-9282-d53bf710c78e.gif)

As you can see in the gif normally the menu should appear on right not left and also the tab bar color have changed normally it's orange not white.

**Comment by haducloc** [comment]
Try set drawerController.drawerDirection = .Right BEFOR mainViewController set

       // Init drawerController BEFOR main/drawerViewController set
       drawerController.drawerDirection = .Right
       drawerController.drawerWidth     = 200

       drawerController.mainViewController = UINavigationController(
            rootViewController: tabBarController
        )
        drawerController.drawerViewController = menuController

**Comment by ykyouhei** [comment]
@chlebta @haducloc 
Thanks! fixed This bug :+1: 
https://github.com/ykyouhei/KYDrawerController/releases/tag/1.1.2
