### ISSUE TITLE
Open/Close issue with storyborad configuration

### ISSUE THREAD

**Issue by panyamred** [ykyouhei/KYDrawerController#29]
if let drawerController = navigationController?.parentViewController as? KYDrawerController {
            drawerController.setDrawerState(.Closed, animated: true)
or
drawerController.setDrawerState(.Opened, animated: true)
        }

navigationController is nil here. So, drawer is not closing / opening.

pan gesture is working perfectly.

main view controller is tabbarcontroller

**Comment by ykyouhei** [comment]
@panyamred Thanks! Can you put a capture of the storyboard ?

**Comment by panyamred** [comment]
I found the issue and solution. It is working now.
