### ISSUE TITLE
Drawer is not opening when coming from notification

### ISSUE THREAD

**Issue by kalyansriram** [ykyouhei/KYDrawerController#32]
I have integrated notifications in my ios app and on click of the notification i should go to the detail screen from list screen. The first list screen contains menu with KYDrawerController and the second screen is pushed into the main viewcontroller's stack. And everything works fine when i click the menu button its opening the menu button and when i click on some item in list its going to the detail screen but when I click on the notification which will directly take me to detail screen and coming back from that screen and clicking the menu button its not opening the menu drawer controller. And when i checked with the debugger the tap method is calling and its going into the KYDrawerController methods. Something fishy is happening here. Kindly help me with some hints why this is happening ?

**Comment by timusus** [comment]
@kalyansriram can you please fork the project and provide a sample of the issue? Impossible to know what's going on with such a specific problem. If you can, happy to reopen the issue.
