### ISSUE TITLE
Does not perform prefersStatusBarHidden when setNeedsStatusBarAppearanceUpdate

### ISSUE THREAD

**Issue by lyc2345** [ykyouhei/KYDrawerController#34]
Hello guys.
This Drawer is so good to use it. I like this style than others.
But I have a issue, I want to hide status bar when drawer is opened.
I override prefersStatusBarHidden but this is never called. even on viewDidLoad.

Could anybody help me to figure this out, Please?
Any help would be thankful.

**Comment by AustinChou** [comment]
@lyc2345 I think you should override prefersStatusBarHidden in the subclass of KYDrawerController since it just add the drawer and main view controller's view into KYDrawerController's view. And change that value when drawer opened and closed.
