### ISSUE TITLE
How to open menu from sidemenu click swift

### ISSUE THREAD

**Issue by cloudjanak** [ykyouhei/KYDrawerController#35]

**Comment by danielsaidi** [comment]
The example project shows you how to use the `navigationController` parent, cast it to `KYDrawerController` and call `setDrawerState(...)`.

However, if you don't have a navigation controller, you can use the following in your main view controller:

```    
override func didMove(toParentViewController parent: UIViewController?) {
   guard let vc = parent as? KYDrawerController else { return }
   drawerController = vc
}
```

You can then use the drawerController property to set its' state to open.
