### ISSUE TITLE
How to update the main view with drawer menu 

### ISSUE THREAD

**Issue by abdulKarim002** [ykyouhei/KYDrawerController#36]
Hello Sir,
It's really a nice lib and easy to integrate slide menu, but here I am not able to update the main view from drawer view the view is always updated on drawer controller only.

For example, I have four views as follows:-
1- main
2- drawer
   2.1 - in the drawer, there is two button menu ie signup and login
from the main menu I am able to access the drawer menu but when I used to click the menu button the view is updating on drawer menu only and the main view is as it is 
any suggestion..!
Thank you

**Comment by ykyouhei** [comment]
@abdulKarim002 Hi! 
The following implementation or would be helpful?
[DrawerSample.zip](https://github.com/ykyouhei/KYDrawerController/files/171014/DrawerSample.zip)
