### ISSUE TITLE
Drawer in tab bar

### ISSUE THREAD

**Issue by happiehappie** [ykyouhei/KYDrawerController#39]
How do I implement a drawer in my tab bar, right now my implementation renders my tab bar above the drawer, is it even possible to use this framework in a tab bar in the first place?

**Comment by ykyouhei** [comment]
Does this become the answer ?
[DrawerSample.zip](https://github.com/ykyouhei/KYDrawerController/files/170974/DrawerSample.zip)

**Comment by happiehappie** [comment]
Sorry I only see a tab bar with Favourites and More

**Comment by happiehappie** [comment]
<img width="432" alt="screen shot 2016-03-16 at 2 09 34 am" src="https://cloud.githubusercontent.com/assets/6497131/13788787/28f72e5e-eb1c-11e5-8161-776049ffa706.png">
Basically this is my current problem, my tab bar is "on top" of the drawer

**Comment by ykyouhei** [comment]
Please try this sample to the reference
[Sample.zip](https://github.com/ykyouhei/KYDrawerController/files/275902/Sample.zip)

**Comment by BhavinBhadani** [comment]
@ykyouhei yes but then it doesn't give simplest code to open drawer with above simple hierarchy of button click means we first need to find Drawercontroller then only we can active state to open
