### ISSUE TITLE
How to change first backround view

### ISSUE THREAD

**Issue by dtilve** [ykyouhei/KYDrawerController#40]
Hi! I need to change the first view when the drawer loads (and the user still hasn't selected any tab or even open the drawer menu). It depends on the view the menu loads, i.e.: if I load login, then the profile should appear and the drawer should be available. How can I do it so it shows the profile and not a white screen? Thank you very much and excelent job with this framework.

**Comment by ykyouhei** [comment]
@dtilve Hi! Please try this sample to the reference
[Sample 2.zip](https://github.com/ykyouhei/KYDrawerController/files/275901/Sample.2.zip)
