### ISSUE TITLE
Support Example For using with UITabBarController?

### ISSUE THREAD

**Issue by htarwara6245** [ykyouhei/KYDrawerController#41]
First of all,Thanks for all of your hard work.Really love it to try.
Your gif image show that your view controller is also supported for embedding with UITabBarController.

But,I really need some help with demo project.So,Any Help with UITabBarController?Because i want to build App like Google+ current version for now.Plus,I want to navigate directly from left menu to uitabbar item.
Eg.,If I tapped one of the menu from left menu,it navigate to appropriate UITabBarItem

If you have anytime,can you take a look at this?because we all have our circumstances,our life.
So,Any Demo Example for that?Storyboard or code?

Any Help?Thanks.

**Comment by ykyouhei** [comment]
@htarwara6245 Hi! Please try this sample to the reference!
[Sample.zip](https://github.com/ykyouhei/KYDrawerController/files/275881/Sample.zip)
(Xcode7.3.1)
