### ISSUE TITLE
Drawer width autolayout

### ISSUE THREAD

**Issue by Ravichandrane** [ykyouhei/KYDrawerController#46]
Hi kyo,

Thanks for your library, I'm wondering how can I use autolayout to update the drawer width ? 

Thanks,
Ravi.

**Comment by mhtranbn** [comment]
Please explan this to other people can autolayout. thanks @Ravichandrane

**Comment by Ravichandrane** [comment]
Hi @mhtranbn, 

Yeah sure, I just used **UIScreen.mainScreen().scale**  to determine which iPhone. 

Exemple : 
let scale = UIScreen.mainScreen().scale
```

if let drawerController = navigationController?.parentViewController as? DrawerController {
drawerController.delegate = self
switch scale {
 case 2: 
  drawerController.drawerWidth = YOUR WIDTH
default:
  drawerController.drawerWidth = YOUR WIDTH
} 
drawerController.setDrawerState(.Opened, animated: true)
}

```
**case 2** meaning: iPhone5(s/c/SE), iPhone 6(S)
**default** for other devices : iPhone 6+(S)

**Comment by mhtranbn** [comment]
It not autolayout, but its ok. :D , thanks @Ravichandrane
