### ISSUE TITLE
Hide tabbar on push is not working.

### ISSUE THREAD

**Issue by DesmondPang** [ykyouhei/KYDrawerController#55]
Hide tabbar on push is not working. 
TabbarController -> KYDrawerController - > MyUITableViewController -> push to detail view

I want to hide the UITabBar on the detail View. It does work.

**Comment by eikebartels** [comment]
same for me

**Comment by ykyouhei** [comment]
Perhaps `Hide tabbar on push` does not work only in the navigation controller to manage the tab bar controller.

**Comment by ykyouhei** [comment]
If you wish to achieve it, you need to configuration as shown in FIG.
<img width="1240" alt="2016-10-02 1 39 23" src="https://cloud.githubusercontent.com/assets/5757351/19015555/c879689e-8841-11e6-9b7a-0c2f298a679b.png">

**Comment by timusus** [comment]
This looks like an iOS development question rather than something that specifically relates to `KyDrawerController`, thus closing.
