### ISSUE TITLE
Unknown class KYDrawerController in Interface Builder file.

### ISSUE THREAD

**Issue by sonysum** [ykyouhei/KYDrawerController#57]
I try to use via pod install
when run it have error "Unknown class KYDrawerController in Interface Builder file."
why it like that?

**Comment by ykyouhei** [comment]
@sonysum Hi!
Do you set the module column?
![2016-07-17 19 28 26](https://cloud.githubusercontent.com/assets/5757351/16900085/c74c4f96-4c54-11e6-862d-6971fb0d3778.png)

**Comment by sonysum** [comment]
i did not set  module column
should i set it or not?

**Comment by ykyouhei** [comment]
You should 👍

**Comment by sonysum** [comment]
Ok it work Now Thanks
