### ISSUE TITLE
Drawer width smaller in status bar

### ISSUE THREAD

**Issue by alvinmeimoun** [ykyouhei/KYDrawerController#59]
HI,

I followed the Interface Builder instruction, but i got this strange render and i didn't found anything to solve this

<img width="245" alt="capture d ecran 2016-07-27 a 18 33 23" src="https://cloud.githubusercontent.com/assets/3252195/17183680/e895a1b2-5428-11e6-962d-ecd98c2ad58b.png">

The KYDrawerController is the first controller after a modal segue (i can't place it at entry point because i've the login screen) and the problem appear with and without drawer width setted

**Comment by ykyouhei** [comment]
It was unable to reproduce the problem.

<img width="673" alt="2016-10-02 1 58 01" src="https://cloud.githubusercontent.com/assets/5757351/19015703/47be780e-8844-11e6-8fc5-cb9b22a130b0.png">

![test](https://cloud.githubusercontent.com/assets/5757351/19015727/d2e92dfc-8844-11e6-9715-511c946aeb09.gif)

**Comment by timusus** [comment]
@alvinmeimoun are you able to create a fork which demonstrates this issue? If so, we will reopen.
