### ISSUE TITLE
Getting many error on Xcode 8, Swift 3

### ISSUE THREAD

**Issue by sovannarithsok** [ykyouhei/KYDrawerController#68]
How to use 'KYDrawerController' for supporting swift 3?

**Comment by sovannarithsok** [comment]
Oh, it works when I use this:


            pod 'KYDrawerController', :git => "https://github.com/ykyouhei/KYDrawerController", :branch => "master"

**Comment by ykyouhei** [comment]
@sovannarithsok  Hi!
push the latest version (2.0.0) to cocoapods.
