### ISSUE TITLE
Support for iOS 10

### ISSUE THREAD

**Issue by pranav18** [ykyouhei/KYDrawerController#69]
I have upgraded my system and Xcode to 8.
When I am building app in iOS 10 with swift 3. KYDrawerController giving issue.

Can you please provide me support for swift 3.

**Comment by ykyouhei** [comment]
@pranav18 Hi. Supported iOS10 and Swift3 in  v2.0.1
https://github.com/ykyouhei/KYDrawerController/releases/tag/2.0.1
