### ISSUE TITLE
Error in Code

### ISSUE THREAD

**Issue by cesarmtz93** [ykyouhei/KYDrawerController#70]
Hi I´ve set up the project of a uitabcontroller and the drawer as the issue #41, but i have a view controller with a button action performing the next code 

        let drawer = self.navigationController!.parent?.parent as! KYDrawerController
        drawer.setDrawerState(.opened, animated: true)

im getting this error "Could not cast value of type 'KYDrawerController.KYDrawerController' (0x1012c3b00) to 'renti.KYDrawerController' (0x100cb5db0)."

**Comment by ykyouhei** [comment]
As indicated by the error statement, `self.navigationController!.parent?.parent` is not a `KYDrawerController` type.
Please understand viewcontroller hierarchy.
https://developer.apple.com/library/content/featuredarticles/ViewControllerPGforiPhoneOS/TheViewControllerHierarchy.html#//apple_ref/doc/uid/TP40007457-CH33-SW1

**Comment by cesarmtz93** [comment]
I don't think it's about the hierarchy, because i had it this way since swift 2.2 and now that it was updated and you said in the ticket #57, that we need to set module column, now it breaks 

because if I print this line self.navigationController!.parent?.parent i get Optional(<KYDrawerController.KYDrawerController: 0x7fc0add0b270>)

so it's module.class and the error Could not cast value of type 'KYDrawerController.KYDrawerController'  to 'renti.KYDrawerController' , so it´s a casting problem between that.

**Comment by ykyouhei** [comment]
It will work without problems in this sample code.
Please check the implementation or configuration！
[Sample.zip](https://github.com/ykyouhei/KYDrawerController/files/491419/Sample.zip)

**Comment by cesarmtz93** [comment]
Hi, Thanks for the Sample, but i see we have a misunderstanding, 

I modified your sample to what I´m trying to achieve, just so that you can notice the error that i´m getting! 

I do appreciate all the help that you´re giving me!

[Sample.zip](https://github.com/ykyouhei/KYDrawerController/files/491431/Sample.zip)

**Comment by ykyouhei** [comment]
viewController hierarchy is wrong!!
```
@IBAction func buttonDidTap(_ sender: UIButton) {
        let drawer = tabBarController?.parent as! KYDrawerController
        drawer.setDrawerState(.opened, animated: true)
 }
```

Here is not the place to ask questions. It is the place to report the issue!!
First of all, please check the cause of the problem on their own.

https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde
