### ISSUE TITLE
error in Xcode 8 swift 3

### ISSUE THREAD

**Issue by sonysum** [ykyouhei/KYDrawerController#74]
i got an error 
Module compiled with Swift 2.3 cannot be imported in Swift 3.0
how to fix?

**Comment by ColdLogical** [comment]
The source code will have to be updated to 3.0.

**Comment by psi-gh** [comment]
Will it be updated?

**Comment by RubenEsposito** [comment]
Is anybody working on a Swift 3.0 version?

**Comment by AmitBluepi** [comment]
I worked on swift 3.0 and my Page view controller is not initial controller.
Not the issue is pagination style is always in curl not scroll. I want to use this as scroll transition.
Plz help in this.

**Comment by timusus** [comment]
Closed thanks to #104 (and possibly others)
