### ISSUE TITLE
Main Storyboard segue is nil

### ISSUE THREAD

**Issue by Salmancs43** [ykyouhei/KYDrawerController#79]
I am trying to use KYDrawerController but the main and drawer segue is nil. I tried it a lot but i never found the solution. I am a attaching my storyboard picture. Please help me with this issue. Thanks
<img width="748" alt="screen shot 2016-12-23 at 3 13 18 am" src="https://cloud.githubusercontent.com/assets/23050315/21442153/d858b208-c8bd-11e6-8766-6acd253c6c4d.png">
<img width="807" alt="screen shot 2016-12-23 at 3 13 37 am" src="https://cloud.githubusercontent.com/assets/23050315/21442156/d8b9a298-c8bd-11e6-95ed-26c4a86a21e0.png">
![Uploading Screen Shot 2016-12-23 at 3.13.45 AM.png…]()

**Comment by mhtranbn** [comment]
me too! please supporst thank you

**Comment by ultrabuckner** [comment]
do u have any project sample. I still fail to apply this library.

**Comment by ykyouhei** [comment]
@mhtranbn 
Please try setting `KYDrawerController` in the module.
<img width="748" alt="d858b208-c8bd-11e6-8766-6acd253c6c4d" src="https://cloud.githubusercontent.com/assets/5757351/21601347/cc88ca2c-d1cc-11e6-93e7-5978ff6fae67.png">

**Comment by Salmancs43** [comment]
Thanks. One more thing can this library blur the back view controller?

**Comment by ykyouhei** [comment]
Make the background of the drawerViewController transparent and add UIVisualEffectView.
