### ISSUE TITLE
Delegate by drawer state

### ISSUE THREAD

**Issue by seapy** [ykyouhei/KYDrawerController#8]
Hi, 

`KYDrawerController` is nice drawer. 
but needed delegate, by drawer state like `DrawerState.Opened` or `DrawerState.Closed`

`func kyDrawerControllerStateChanged(state: DrawerState)`

**Comment by ykyouhei** [comment]
Hi, @seapy 
Added the delegate methods in [v1.0.3](https://github.com/ykyouhei/KYDrawerController/releases/tag/1.0.3) :+1:

**Comment by seapy** [comment]
Thanks. it works :+1:
