### ISSUE TITLE
How to replace page ?

### ISSUE THREAD

**Issue by delochi** [ykyouhei/KYDrawerController#84]
I wanna to replace page when i click list menu in drawer menu. I am is new bee, help please
thanks

**Comment by colincameron** [comment]
You can set the `mainViewController` property to your new view controller.

**Comment by MuqThe2nd** [comment]
The frame changes. I have a tabBarController in which each viewController is embedded in a navigationController. Please help.

**Comment by timusus** [comment]
This is an iOS development question, not specifically related to `KyDrawerController`, thus closing.
