### ISSUE TITLE
Swipe to open not working when main controller is UINavigationController

### ISSUE THREAD

**Issue by axlalvaro** [ykyouhei/KYDrawerController#88]
Hi, so my main controller is a UINavigationController, but when I swipe from the edge of the screen, the drawer does not show up.

Any help on solving this?

Thanks!

**Comment by axlalvaro** [comment]
I figured out that it works if I disable the pop gesture recognizer of the navigation controller:
`self.navigationController?.interactivePopGestureRecognizer?.isEnabled = false`

**Comment by ykyouhei** [comment]
@axlalvaro 
Because the gesture conflicts, the above mentioned countermeasure is correct
