### ISSUE TITLE
Push or set other views from left menu view (probably table row selection)

### ISSUE THREAD

**Issue by PrakashMaharjan** [ykyouhei/KYDrawerController#98]
Hi,
Is there way to push to other view or set from view controller?
The example only shows change of background color, which does not assist of moving to other views.
How can we push to other views? I can't see it in documentation as well.
The help would be very much appreciable.
Thanks

**Comment by PrakashMaharjan** [comment]
I found solution to push view as following..

let storyboard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil) 
let newVC: NewViewController = storyboard.instantiateViewController(withIdentifier: "newVc") as! NewViewController   // view to set 
let drawerController = self.navigationController?.parent as? KYDrawerController
let navController = UINavigationController.init(rootViewController: newVC)
drawerController?.mainViewController=navController
drawerController?.setDrawerState(KYDrawerController.DrawerState.closed, animated: true)

**Comment by pranitk** [comment]
Whenever I open a UINavigationController from the DrawerController I get weird margins and the viewcontroller's view appears to be zoomed.

**Comment by prayasht** [comment]
Took me a while to figure it out, but this is what works for me. Assuming your setup in `AppDelegate` is following the README, In the MenuTableView's `didSelectItemAt` delegate method I put: 

```swift
// Cast child controller of parent as UINavigationController
guard let drawerController = parent as? KYDrawerController,
            let navController = drawerController.mainViewController as! UINavigationController? else { return }

// Push onto the stack
navController.pushViewController(UIViewController(), animated: true)
```

**Comment by timusus** [comment]
This is an iOS development question, rather than a KyDrawerController issue. Welcome the discussion, but closing as not relevant to the project.
